# Generated by Django 5.0.3 on 2024-09-06 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('ffjournal', '0003_alter_league_draft_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='leagues',
            field=models.ManyToManyField(related_name='profiles', to='ffjournal.league'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=69, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
