# Generated by Django 5.0.3 on 2024-09-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffjournal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='latest_league_winner_roster_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
