# Generated by Django 5.0.3 on 2024-09-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffjournal', '0002_alter_league_latest_league_winner_roster_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='draft_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='previous_league_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='waiver_budget',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
