# Generated by Django 5.0.3 on 2024-09-06 08:35

import ffjournal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffjournal', '0003_alter_league_draft_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='owner_id',
            field=models.CharField(default=ffjournal.models.generate_default_owner_id, max_length=255),
        ),
    ]
