# Generated by Django 5.0.3 on 2024-09-09 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffjournal', '0004_alter_roster_owner_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('pts_ppr', models.IntegerField(blank=True, null=True)),
                ('opponent', models.CharField(blank=True, max_length=255, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ffjournal.player', to_field='player_id')),
            ],
            options={
                'unique_together': {('week', 'player')},
            },
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('pts_ppr', models.IntegerField(blank=True, null=True)),
                ('opponent', models.CharField(blank=True, max_length=255, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ffjournal.player', to_field='player_id')),
            ],
            options={
                'unique_together': {('week', 'player')},
            },
        ),
    ]
