# Generated by Django 5.0.3 on 2024-09-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffjournal', '0005_playerprojection_playerstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprojection',
            name='pts_ppr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
