# Generated by Django 5.0.3 on 2024-09-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffjournal', '0006_alter_playerprojection_pts_ppr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstats',
            name='pts_ppr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
