# Generated by Django 5.0.3 on 2024-09-09 18:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffjournal', '0007_alter_playerstats_pts_ppr'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='players',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='matchup',
            name='players_points',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchup',
            name='starters',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='matchup',
            name='starters_points',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='matchup_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='roster_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
