# Generated by Django 5.0.3 on 2024-09-10 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffjournal', '0009_alter_league_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, default=''),  # Add a default value
            # Alternatively, use null=True to make it nullable:
            # field=models.CharField(max_length=255, null=True),
        ),
    ]
