# Generated by Django 5.0.3 on 2024-09-10 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffjournal', '0010_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='Placeholder Title', max_length=255),
        ),
    ]
