# Generated by Django 5.1 on 2024-09-10 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffjournal', '0011_alter_article_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingDownPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ffjournal.player', to_field='player_id')),
            ],
        ),
        migrations.CreateModel(
            name='TrendingUpPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ffjournal.player', to_field='player_id')),
            ],
        ),
    ]
