# Generated by Django 5.1 on 2024-09-10 06:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffjournal', '0012_trendingdownplayer_trendingupplayer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendingdownplayer',
            name='player_id',
        ),
        migrations.RemoveField(
            model_name='trendingupplayer',
            name='player_id',
        ),
        migrations.AddField(
            model_name='trendingdownplayer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trendingdownplayer',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ffjournal.player'),
        ),
        migrations.AddField(
            model_name='trendingupplayer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trendingupplayer',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ffjournal.player'),
        ),
    ]
