# Generated by Django 5.0.3 on 2024-09-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffjournal', '0013_remove_trendingdownplayer_player_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendingdownplayer',
            name='player',
        ),
        migrations.AddField(
            model_name='trendingdownplayer',
            name='player_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
